import { type NextPage } from "next";
import Head from "next/head";
import axios from "axios";
import dynamic from "next/dynamic";

const MapLibree = dynamic(() => import("../components/maplibre"), {
  ssr: false,
});

const Home: NextPage = () => {
  axios
    .get(
      // `https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lng}`
      `https://api.open-meteo.com/v1/forecast?latitude=41.09&longitude=28.98&current_weather=true&timezone=auto`
    )
    .then((res) => {
      // console.log(res.data);
    })
    .catch((err) => {
      console.log(err);
    });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MapLibree />
    </>
  );
};

export default Home;
